### ISSUE TITLE
Auto discovery for logs by directory

### ISSUE THREAD

**Issue by nritholtz** [awslabs/ecs-cloudwatch-logs#1]
As far as I understand, in order for this agent to recognize the log file, you must specify the file name in the conf file. However, this approach, as I see it, requires me to change the conf every time I add a new custom log file in my log directory. 

Is it possible to provide the ability to specify a log directory and have the agent auto discover the `.log` files within the specified directory? The configuration settings should be propagated to each found log file. The log_stream_name should take the configured standard and append the actual found log file name.

**Comment by cbbarclay** [comment]
I assume you are talking about the CloudWatch Logs config:
http://bit.ly/1Gmsj1E

In this case, you could use a wildcard for the “File” parameter as explained here:
http://amzn.to/1Qj5imM

“file Specifies log files that you want to push to CloudWatch Logs. File can point to a specific file or multiple files (using wildcards such as /var/log/system.log*). Only the latest file is pushed to CloudWatch Logs based on file modification time. We recommend that you use wildcards to specify a series of files of the same type, such as access_log.2014-06-01-01, access_log.2014-06-01-02, and so on, but not multiple different kinds of files, such as access_log_80 and access_log_443. To specify multiple different kinds of files, add another log stream entry to the configuration file so each kind of log files goes to different log group. Zipped files are not supported."
